services:
  transformation.argument_transformer.behat2_storage:
    class: rdx\behat2\ext\Behat2StorageArgumentTransformer
    tags:
      -  { name: transformation.argument_transformer, priority: 100 }
